languaes: node_js
node_js:
  - "lts/*"
dist: trusty
sudo: false
branches:
  only:
    - master
addons:
  chrome: stable
# cache:
#   directories:
    # - ./node_modules
install:
  - nvm install lts
  - nvm use lts
  - npm i -g npm@latest
  - npm install -g @angular/cli@latest
  - npm ci
script:
- npm run lint:lib
- npm run lint:app:quiz
- npm run test:lib
- npm run build:lib
- npm run test:app:quiz
- npm run webdriver-update-ci
- npm run e2e:app:quiz -- --webdriver-update=false
- npm run build:app:quiz
deploy:
  skip_cleanup: true
  provider: firebase
  edge: true
  token:
    secure: NeluE7CQpCO9P4k0WXsynk5a2eQlUfSEkq4u++Vw3XLXg55I6DJtVuQEb/rTShA4AETRokC0Y/UdBb/2vPh5FKpR+4NL+gadSUayQmOCcjVotWcRQNDtbJ91uVGllZ8vdcv4o6DIa5llDVkrsco0H6yoe/fzXAq7bXEkFQZBfjF0LnSmXfcNPfrFzVBJ2XyGDu0zqxH7S44i9E/KFna1fEsiPYDHdX/r3ychnFfab0Og4zyDU+sIKXTUTkNjX0E0rVkQPYxH8VjwjQi7c/SEnKf7keM2bpailRpaDu4fUccK8l3aa7IcOYzSwlA3EsFZ5xHPCS6YaNZXKoRtEz04ignh/W82KqnLHuihPgUmdIExLfi+Zzq0e00LDqf72uVdiCDqat/XGuGqKBw5HO399V6r1chIW3pfoRcVfv0QXKElDgyEyike1376cDkW+3mtnGyHGZe8hBBvMuJmkqY/QrlhmCUMqL/T2dH6BR0vrdJEjpSLjXw+lTVsRNNPYzReSPTia1QOYwi41LO10FuMqZS0f0E1wTbX9mVaOjDsxvq+8y2GAFMs8B7SXyG5Cj+zM262kKfcTqYZFcYjQhHCKuQmI9SGZb46cJKOUC5cHC6nw5GfslcFjkDyLBsWFBwvLc8jJq6VmUFxszGeIPW5yhjtQm9KusL6GSKq9WNEpZY=
  project: "angular-quiz-33472"
