export const Technologies = {
  android: 'android',
  angular: 'angular',
  angularjs: 'angularjs',
  aws: 'aws',
  bootstrap4: 'bootstrap4',
  cordova: 'cordova',
  electron: 'electron',
  electronjs: 'electron',
  firebase: 'firebase',
  gcp: 'gcp',
  go: 'go',
  golang: 'go',
  ionic: 'ionic',
  ios: 'ios',
  java: 'java',
  nest: 'nest',
  nestjs: 'nest',
  ngrx: 'ngrx',
  nx: 'nx',
  // https://nodejs.org/en/about/resources/
  node: 'nodejs',
  nodejs: 'nodejs',
  neo4j: 'neo4j',
  netcore: 'netcore',
  nativescript: 'nativescript',
  // https://github.com/webmaxru/progressive-web-apps-logo -> https://diekus.com/logo-pwinter/
  pwa: 'pwa',
  python: 'python',
  rx: 'rxjs',
  rxjs: 'rxjs',
  // https://github.com/sass/sass-site/blob/master/source/assets/img/logos/logo.svg
  sass: 'sass',
  scss: 'sass',
  ts: 'typescript',
  tensorflow: 'tensorflow',
  typescript: 'typescript',
  // https://github.com/webrtc/webrtc-org -> https://github.com/webrtc/webrtc-org/blob/gh-pages/assets/images/webrtc-logo-vert.svg
  webrtc: 'webrtc',
};
