# Javascript Node CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-javascript/ for more details
#
version: 2
jobs:
  build:
    branches:
      ignore:
        - gh-page
    docker:
      # specify the version you desire here
      - image: circleci/node:10.11-browsers

      # Specify service dependencies here if necessary
      # CircleCI maintains a library of pre-built images
      # documented at https://circleci.com/docs/2.0/circleci-images/
      # - image: circleci/mongo:3.4.4

    working_directory: ~/repo
    environment:
      - SOURCE_BRANCH: master
      - TARGET_BRANCH: gh-pages
      - TERM: xterm
    steps:
      - checkout
      - add_ssh_keys:
          fingerprints:
            - "84:0d:57:22:63:3b:0c:1b:ee:85:5d:a2:13:c0:30:5c"
      # Download and cache dependencies
      - restore_cache:
          keys:
          - v1-dependencies-{{ checksum "package.json" }}
          # fallback to using the latest cache if no exact match is found
          - v1-dependencies-

      - run: npm run ci

      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "package.json" }}

      # run lint!
      - run: npm run lint:lib
      - run: npm run lint:app:who

      # run lib unit tests!
      - run: npm run test:lib

      # run build lib!
      - run: npm run build:lib

      # run app unit tests!
      - run: npm run test:app:who

      # fix chrome driver version
      - run: npm run webdriver-update-ci

      # run e2e!
      - run: npm run e2e:app:who

      # run cypress!
      # - run: npm run cypress:run

      # run build
      - run: npm run build:gh

      # deploy to GH page
      - deploy:
          name: Deploy
          command: bash ./deploy.sh


