# Javascript Node CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-javascript/ for more details
#
version: 2
jobs:
  build:
    docker:
      # specify the version you desire here
      - image: circleci/node:10.11-browsers

      # Specify service dependencies here if necessary
      # CircleCI maintains a library of pre-built images
      # documented at https://circleci.com/docs/2.0/circleci-images/
      # - image: circleci/mongo:3.4.4

    working_directory: ~/repo

    steps:
      - checkout

      # Download and cache dependencies
      - restore_cache:
          keys:
          - v1-dependencies-{{ checksum "package.json" }}
          # fallback to using the latest cache if no exact match is found
          - v1-dependencies-

      - run: yarn install

      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "package.json" }}

      # run lint!
      - run: yarn lint

      # run unit tests!
      - run: yarn test

      # run e2e tests!
      - run: yarn e2e -- --protractor-config=./e2e/protractor-ci.conf.js

      # run build
      - run: yarn build:gh

      # deploy to GH page
      - run: yarn ngh --repo=https://$GH_TOKEN@github.com/perjerz3434/who-use-angular-in-thailand.git --dir=dist/who-use-angular-in-thailand --name=PerJerZ --email=perjerz3434@gmail.com


