export const Technologies = {
  android: 'android',
  angular: 'angular',
  angularjs: 'angularjs',
  electron: 'electron',
  electronjs: 'electron',
  firebase: 'firebase',
  gcp: 'gcp',
  ionic: 'ionic',
  ios: 'ios',
  java: 'java',
  nest: 'nest',
  nestjs: 'nest',
  ngrx: 'ngrx',
  nativescript: 'nativescript',
  python: 'python',
  rx: 'rxjs',
  rxjs: 'rxjs',
  ts: 'typescript',
  tensorflow: 'tensorflow',
  typescript: 'typescript',
};
